#ifndef PROPERTIES_H
#define PROPERTIES_H

enum UnitType {
	SOLDIER,
	ROGUE,
	WIZARD,
	HEALER,
	PRIEST,
	VAMPIRE,
	WEREWOLF,
	BERSERKER,
	WARLOCK,
	NECROMANCER,
	DEMON,
};

enum Hp {
	HP_SOLDIER = 70,
	HP_ROGUE = 100,
	HP_WIZARD = 60,
	HP_HEALER = 80,
	HP_PRIEST = 110,
	HP_VAMPIRE = 100,
	HP_BERSERKER = 130,
	HP_WEREWOLF = 90,
	HP_WOLF = 120,
	HP_WARLOCK = 100,
	HP_NECROMANCER = 95,
	HP_DEMON = 50,
};

enum Dmg {
	DMG_SOLDIER = 20,
	DMG_ROGUE = 35,
	DMG_WIZARD = 15,
	DMG_HEALER = 15,
	DMG_PRIEST = 10,
	DMG_VAMPIRE = 30,
	DMG_BERSERKER = 25,
	DMG_WEREWOLF = 20,
	DMG_WOLF = 35,
	DMG_WARLOCK = 25,
	DMG_NECROMANCER = 20,
	DMG_DEMON = 10,
};

enum Mana {
	MANA_WIZARD = 100,
	MANA_HEALER = 120,
	MANA_PRIEST = 150,
	MANA_WARLOCK = 110,
	MANA_NECROMANCER = 90,
};

enum SpellName {
	FIREBALL,
	FLASH_HEAL,
};

enum SpellPoints {
	POINTS_FIREBALL = 50,
	POINTS_FLASH_HEAL = 40,
};

enum SpellCost {
	MANA_FIREBALL = 30,
	MANA_FLASH_HEAL = 20,
};

#endif // PROPERTIES_H